/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ICovenant {
    function setResolver(address new_resolver) external;

    function setParameters(uint256 bond_amount, uint256 challenge_stake, uint64 challenge_window) external;

    function pause() external;

    function unpause() external;

    function withdrawTreasury(address to, uint256 amount) external;

    function registerStrategy(string calldata name, string calldata metadata_uri) external returns (uint256);

    function commitEpoch(uint256 strategy_id, uint64 epoch_index, int256 equity, int256 net_flow, bytes32 trades_root, string calldata evidence_uri) external;

    function finalizeEpoch(uint256 strategy_id, uint64 epoch_index) external;

    function challengeEpoch(uint256 strategy_id, uint64 epoch_index, string calldata reason) external;

    function resolveChallenge(uint256 strategy_id, uint64 epoch_index, bool upheld) external;

    function verifyReceipt(uint256 strategy_id, uint64 epoch_index, bytes32[] memory proof, bytes32 receipt) external view returns (bool);

    function strategyCount() external view returns (uint256);

    function config() external view returns (address, address, address, uint256, uint256, uint64, bool, uint256);

    function getStrategy(uint256 strategy_id) external view returns (address, string memory, string memory, uint256, uint8, uint64);

    function getPerformance(uint256 strategy_id) external view returns (int256, int256, int256, uint64, uint64);

    function getCheckpoint(uint256 strategy_id, uint64 epoch_index) external view returns (int256, int256, bytes32, string memory, uint8, uint64, address, uint256);

    error NotAdmin();

    error NotResolver();

    error NotStrategyOwner();

    error ContractPaused();

    error StrategyNotFound();

    error StrategySuspended();

    error EpochNotSequential();

    error EpochUnknown();

    error EpochNotPending();

    error ChallengeWindowElapsed();

    error ChallengeWindowActive();

    error AlreadyChallenged();

    error ZeroAddress();

    error ZeroAmount();

    error TokenTransferFailed();
}
