import type { Abi, Address } from "viem";

/** USDG (Global Dollar, Paxos) ERC-20 addresses. 6 decimals on all chains. */
export const USDG: { arbitrumOne: Address; arbitrumSepolia: Address } = {
  arbitrumOne: "0x004B506865409877C9fA29bfb1ebA929984B9bbC",
  arbitrumSepolia: "0xFFC95faa3d63Cde504a05B567C600B78C0b41892",
};

/**
 * Proven contract ABI (generated by `cargo stylus export-abi`).
 * Keep in sync with contracts/proven/src/lib.rs.
 */
export const provenAbi = [
  {
    type: "function",
    name: "setResolver",
    inputs: [{ name: "new_resolver", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setParameters",
    inputs: [
      { name: "bond_amount", type: "uint256" },
      { name: "challenge_stake", type: "uint256" },
      { name: "challenge_window", type: "uint64" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "pause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "unpause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "withdrawTreasury",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "registerStrategy",
    inputs: [
      { name: "name", type: "string" },
      { name: "metadata_uri", type: "string" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "commitEpoch",
    inputs: [
      { name: "strategy_id", type: "uint256" },
      { name: "epoch_index", type: "uint64" },
      { name: "equity", type: "int256" },
      { name: "net_flow", type: "int256" },
      { name: "trades_root", type: "bytes32" },
      { name: "evidence_uri", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "finalizeEpoch",
    inputs: [
      { name: "strategy_id", type: "uint256" },
      { name: "epoch_index", type: "uint64" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "challengeEpoch",
    inputs: [
      { name: "strategy_id", type: "uint256" },
      { name: "epoch_index", type: "uint64" },
      { name: "reason", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolveChallenge",
    inputs: [
      { name: "strategy_id", type: "uint256" },
      { name: "epoch_index", type: "uint64" },
      { name: "upheld", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "verifyReceipt",
    inputs: [
      { name: "strategy_id", type: "uint256" },
      { name: "epoch_index", type: "uint64" },
      { name: "proof", type: "bytes32[]" },
      { name: "receipt", type: "bytes32" },
    ],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  { type: "function", name: "strategyCount", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  {
    type: "function",
    name: "config",
    inputs: [],
    outputs: [
      { name: "admin", type: "address" },
      { name: "resolver", type: "address" },
      { name: "usdg", type: "address" },
      { name: "bond_amount", type: "uint256" },
      { name: "challenge_stake", type: "uint256" },
      { name: "challenge_window", type: "uint64" },
      { name: "paused", type: "bool" },
      { name: "treasury", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStrategy",
    inputs: [{ name: "strategy_id", type: "uint256" }],
    outputs: [
      { name: "owner", type: "address" },
      { name: "name", type: "string" },
      { name: "metadata_uri", type: "string" },
      { name: "bond", type: "uint256" },
      { name: "status", type: "uint8" },
      { name: "created_at", type: "uint64" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPerformance",
    inputs: [{ name: "strategy_id", type: "uint256" }],
    outputs: [
      { name: "equity", type: "int256" },
      { name: "high_water_mark", type: "int256" },
      { name: "cumulative_pnl", type: "int256" },
      { name: "epoch_count", type: "uint64" },
      { name: "finalized_epochs", type: "uint64" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCheckpoint",
    inputs: [
      { name: "strategy_id", type: "uint256" },
      { name: "epoch_index", type: "uint64" },
    ],
    outputs: [
      { name: "equity", type: "int256" },
      { name: "net_flow", type: "int256" },
      { name: "trades_root", type: "bytes32" },
      { name: "evidence_uri", type: "string" },
      { name: "status", type: "uint8" },
      { name: "committed_at", type: "uint64" },
      { name: "challenger", type: "address" },
      { name: "stake", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "StrategyRegistered",
    inputs: [
      { name: "strategy_id", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "bond", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "EpochCommitted",
    inputs: [
      { name: "strategy_id", type: "uint256", indexed: true },
      { name: "epoch_index", type: "uint64", indexed: true },
      { name: "equity", type: "int256", indexed: false },
      { name: "net_flow", type: "int256", indexed: false },
      { name: "trades_root", type: "bytes32", indexed: false },
      { name: "evidence_uri", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "EpochFinalized",
    inputs: [
      { name: "strategy_id", type: "uint256", indexed: true },
      { name: "epoch_index", type: "uint64", indexed: true },
      { name: "pnl", type: "int256", indexed: false },
      { name: "equity", type: "int256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "EpochChallenged",
    inputs: [
      { name: "strategy_id", type: "uint256", indexed: true },
      { name: "epoch_index", type: "uint64", indexed: true },
      { name: "challenger", type: "address", indexed: true },
      { name: "reason", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeResolved",
    inputs: [
      { name: "strategy_id", type: "uint256", indexed: true },
      { name: "epoch_index", type: "uint64", indexed: true },
      { name: "upheld", type: "bool", indexed: false },
      { name: "resolver", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "StrategyStatusChanged",
    inputs: [
      { name: "strategy_id", type: "uint256", indexed: true },
      { name: "status", type: "uint8", indexed: false },
    ],
  },
] as const satisfies Abi;

export type ProvenAbi = typeof provenAbi;
