//! Cross-language conformance: fixtures are generated by the TypeScript SDK
//! (sdk/scripts/gen-fixtures.ts). If either implementation drifts, this fails.

use alloy_primitives::B256;
use merkle_core::{build_proof, build_root, verify_proof};
use serde::Deserialize;

#[derive(Deserialize)]
struct Case {
    leaf: String,
    proof: Vec<String>,
    valid: bool,
}

#[derive(Deserialize)]
struct Fixture {
    size: usize,
    leaves: Vec<String>,
    root: String,
    cases: Vec<Case>,
}

fn parse_b256(s: &str) -> B256 {
    let s = s.strip_prefix("0x").expect("0x prefix");
    let mut bytes = [0u8; 32];
    hex::decode_to_slice(s, &mut bytes).expect("valid hex");
    B256::from(bytes)
}

#[test]
fn typescript_fixtures_verify() {
    let raw = include_str!("fixtures/merkle.json");
    let doc: serde_json::Value = serde_json::from_str(raw).expect("fixture json");
    let fixtures: Vec<Fixture> =
        serde_json::from_value(doc["fixtures"].clone()).expect("fixture shape");

    assert!(!fixtures.is_empty(), "no fixtures");
    for f in &fixtures {
        assert_eq!(f.leaves.len(), f.size);
        let leaves: Vec<B256> = f.leaves.iter().map(|s| parse_b256(s)).collect();

        // root reconstruction matches the TS-computed root
        assert_eq!(
            build_root(&leaves),
            parse_b256(&f.root),
            "root drift at n={}",
            f.size
        );

        for case in &f.cases {
            let leaf = parse_b256(&case.leaf);
            let proof: Vec<B256> = case.proof.iter().map(|s| parse_b256(s)).collect();
            let valid = verify_proof(leaf, &proof, parse_b256(&f.root));
            assert_eq!(
                valid, case.valid,
                "case drift at n={}, leaf={}",
                f.size, case.leaf
            );
        }

        // spot-check proof generation parity for the first leaf
        let rust_proof = build_proof(&leaves, 0);
        let ts_proof: Vec<B256> = f.cases[0].proof.iter().map(|s| parse_b256(s)).collect();
        assert_eq!(rust_proof, ts_proof, "proof bytes drift at n={}", f.size);
    }
}
